[package]
name = "mlc_crab_bot"
version = "2.0.0"
edition = "2021"
license = "GPL-3"

[dependencies]
anyhow = "1.0.82"
poise = "0.6.1"
serde = "1.0.200"
tokio = { version = "1.37.0", features = ["rt-multi-thread"] }
toml = "0.8.12"
