[package]
name = "crab_bot"
version = "2.0.0"
edition = "2021"
license = "GPL-3"
authors = ["Caden64", "Topazstix"]

[dependencies]
futures = "0.3.30"
poise = "0.6.1"
serde = "1.0.200"
tokio = { version = "1.37.0", features = ["rt-multi-thread"] }
toml = "0.8.12"
log = "0.4.21"
serde_json = "1.0.117"
regex = "1.10.4"
chrono = "0.4.38"
chrono-tz = "0.9.0"
rss = "2.0.8"
reqwest = "0.12.5"