[package]
name = "crab_bot"
version = "3.0.0"
edition = "2021"
license = "GPL-3"
authors = ["Caden64", "Topazstix"]

[dependencies]
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
poise = "0.6.1"
reqwest = "0.12.12"